<?php
define('BASE_PATH', dirname(__DIR__) . DIRECTORY_SEPARATOR);
define('CONFIG_PATH', BASE_PATH . 'config' . DIRECTORY_SEPARATOR);
define('APP_PATH', BASE_PATH . 'app' . DIRECTORY_SEPARATOR);
define('CONTROLLER_PATH', APP_PATH . 'controllers' . DIRECTORY_SEPARATOR);
define('MODEL_PATH', APP_PATH . 'models' . DIRECTORY_SEPARATOR);
define('VIEW_PATH', APP_PATH . 'views' . DIRECTORY_SEPARATOR);
define('SERVICE_PATH', APP_PATH . 'services' . DIRECTORY_SEPARATOR);
define('HELPER_PATH', APP_PATH . 'helpers' . DIRECTORY_SEPARATOR);
define('STORAGE_PATH', APP_PATH . 'storage' . DIRECTORY_SEPARATOR);
define('PUBLIC_PATH', BASE_PATH . 'public' . DIRECTORY_SEPARATOR);
define('INSTALL_PATH', BASE_PATH . 'install' . DIRECTORY_SEPARATOR);
define('API_PATH', BASE_PATH . 'api' . DIRECTORY_SEPARATOR);
define('VENDOR_PATH', BASE_PATH);

define('INSTALLER_LOCK_FILE', STORAGE_PATH . 'installed.lock');
