<?php
class SecurityKeysController
{
    public function index()
    {
        $auth = new Auth();
        $auth->requireAdmin();

        $keyModel = new SecurityKey();
        $search = $_GET['search'] ?? '';
        $sort = $_GET['sort'] ?? 'created_at';
        $order = $_GET['order'] ?? 'DESC';
        $keys = $keyModel->getAll(null, $search, $sort, $order);

        $keysData = $keys['data'] ?? $keys;
        $heroId = 'security_keys';
        $heroTitle = 'Security Keys';
        $heroIcon = 'fas fa-key';
        $heroSubtitle = 'Manage API security keys &mdash; <strong>' . ($keys['total'] ?? count($keysData)) . ' total keys</strong>';
        $heroStats = [
            ['value' => $keys['total'] ?? count($keysData), 'label' => 'Total Keys', 'style' => 'color:var(--blue-primary);font-size:1.1rem;'],
        ];

        $title = 'Security Keys';
        $active_menu = 'security_keys';
        $app_name = 'SMTP Management Platform';
        $app_version = '1.0.0';

        ob_start();
        include VIEW_PATH . 'security_keys/index.php';
        $content = ob_get_clean();
        include VIEW_PATH . 'layouts/main.php';
    }

    public function create()
    {
        $auth = new Auth();
        $auth->requireAdmin();

        if ($_SERVER['REQUEST_METHOD'] === 'POST') {
            $keyModel = new SecurityKey();
            $deptId = $_POST['department_id'];
            $keyModel->create([
                'department_id' => $deptId,
            ]);
            $deptName = '';
            if ($deptId) {
                $dm = new Department();
                $d = $dm->getById($deptId);
                $deptName = $d['name'] ?? '';
            }
            notifyAllUsers(
                'New Security Key Generated',
                'A new security key has been generated by ' . ($_SESSION['full_name'] ?? $_SESSION['username'])
                . ($deptName ? " for department: " . $deptName : '') . '.'
            );
            flash('success', 'Security key generated successfully.');
            header('Location: ' . BASE_URL . 'security_keys');
            exit;
        }

        $deptModel = new Department();
        $departments = $deptModel->getAll('active');
        $edit_mode = false;
        $key = [];

        $title = 'Generate Security Key';
        $active_menu = 'security_keys';
        $app_name = 'SMTP Management Platform';
        $app_version = '1.0.0';

        ob_start();
        include VIEW_PATH . 'security_keys/form.php';
        $content = ob_get_clean();
        include VIEW_PATH . 'layouts/main.php';
    }

    public function edit()
    {
        $auth = new Auth();
        $auth->requireAdmin();

        $keyModel = new SecurityKey();
        $id = $_GET['id'] ?? 0;

        if ($_SERVER['REQUEST_METHOD'] === 'POST') {
            $keyModel->update($id, [
                'department_id' => $_POST['department_id'],
                'status'        => $_POST['status'] ?? 'active',
            ]);
            flash('success', 'Security key updated successfully.');
            header('Location: ' . BASE_URL . 'security_keys');
            exit;
        }

        $key = $keyModel->getById($id);
        if (!$key) {
            flash('error', 'Key not found.');
            header('Location: ' . BASE_URL . 'security_keys');
            exit;
        }

        $deptModel = new Department();
        $departments = $deptModel->getAll('active');
        $edit_mode = true;

        $title = 'Edit Security Key';
        $active_menu = 'security_keys';
        $app_name = 'SMTP Management Platform';
        $app_version = '1.0.0';

        ob_start();
        include VIEW_PATH . 'security_keys/form.php';
        $content = ob_get_clean();
        include VIEW_PATH . 'layouts/main.php';
    }

    public function delete()
    {
        $auth = new Auth();
        $auth->requireAdmin();

        $id = $_GET['id'] ?? 0;
        $keyModel = new SecurityKey();
        $key = $keyModel->getById($id);
        $keyModel->delete($id);
        if ($key) {
            $deptName = $key['department_name'] ?? '';
            notifyAllUsers(
                'Security Key Deleted',
                'A security key has been deleted by ' . ($_SESSION['full_name'] ?? $_SESSION['username'])
                . ($deptName ? " for department: " . $deptName : '') . '.'
            );
        }
        flash('success', 'Security key deleted successfully.');
        header('Location: ' . BASE_URL . 'security_keys');
        exit;
    }
}
